-- Tables Sëtu pour Supabase
-- Coller dans l'éditeur SQL de Supabase et exécuter

-- ─── TABLE LIGNES ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lignes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    numero TEXT NOT NULL,
    description TEXT,
    actif BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── TABLE ARRETS ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS arrets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ligne_numero TEXT NOT NULL,
    nom TEXT NOT NULL,
    direction TEXT DEFAULT 'aller',
    ordre INTEGER,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── TABLE SIGNALEMENTS ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS signalements (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id TEXT,
    contact_id UUID,
    ligne TEXT NOT NULL,
    position TEXT NOT NULL,
    lat FLOAT,
    lng FLOAT,
    timestamp TIMESTAMPTZ DEFAULT now(),
    valide BOOLEAN DEFAULT true
);

-- ─── TABLE ABONNEMENTS ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS abonnements (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id TEXT,
    contact_id UUID,
    ligne TEXT NOT NULL,
    arret TEXT,
    heure_alerte TEXT,
    actif BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── INSERT LIGNES ────────────────────────────────────────────
INSERT INTO lignes (numero, description) VALUES ('1A', 'Parcelles Assainies - Leclerc') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('2A', 'Daroukhane - Leclerc') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('6C', 'amberène - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('7O', 'uakam - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('8A', 'éroport - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('9L', 'iberté 6 - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('10L', 'iberté 5 - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('11K', 'eur Massar - Leclerc') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('12G', 'uédiawaye - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('13L', 'iberté 5 - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('14C', 'amp Vert - Leclerc') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('15R', 'ufisque - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('16A', 'Malika - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('16B', 'Malika - Quartier Demba Seck - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('18L', 'iberté 5 - Liberté 5') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('20L', 'iberté 5 - Liberté 5') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('23P', 'arcelles Assainies - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('45M', 'bao - Palais') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('121H', 'LM Grand Yoff - Leclerc') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('208G', 'orom - Rufisque') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('401', '1') ON CONFLICT DO NOTHING;
INSERT INTO lignes (numero, description) VALUES ('319', '9') ON CONFLICT DO NOTHING;

-- ─── INSERT ARRETS ────────────────────────────────────────────
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Pa12-33', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Terrain Acapes', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Centre Médico Social', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Poste De Santé', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Grande Mosquée De Pa', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Pointe', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Cimetiére Saint Lazare De Bétanie', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Castel', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Ambassade De La Guinée Conakry', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Ambassade Du Maroc', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Ucad', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Université Chank Diop', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Av Blaise Diagne / Rue 37', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', '76, Georges Pompidou', 'aller', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Place De L'' Independance', 'aller', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Gare Leclerc', 'aller', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Terminus Parcelles - Assainies', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Pa12-33', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Terrain Acapes', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Centre Médico Social', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Poste De Santé', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Grande Mosquée De Pa', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Pointe', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Cimetiére Saint Lazare De Bétanie', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Castel', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Ambassade De La Guinée Conakry', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Ambassade Du Maroc', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Ucad', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Université Chank Diop', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Av Blaise Diagne / Rue 37', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', '76, Georges Pompidou', 'retour', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Place De L'' Independance', 'retour', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('1A', 'Gare Leclerc', 'retour', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Bvar. De La Libération / Allée Delmas', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Ecolé', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Mosquée', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Ave. Mbacké / Rue 29', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Usine Des Eaux', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Collège Mariama Niasse', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'École 11', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Tally Boubess, 848', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Tally Boumak, 191', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Grand Mosquée De Pikine', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Tribunal De Guediawaye', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Collége Serigne', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Stade Amadou', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Police De Guediawaye', 'aller', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Pompiers De Guédiawaye', 'aller', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Bvard. Tall / Route Corniche', 'aller', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Mairie Hamo5', 'aller', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Gare Routière Daroukhane', 'aller', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Gare Leclerc', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Bvar. De La Libération / Allée Delmas', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Ecolé', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Mosquée', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Ave. Mbacké / Rue 29', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Usine Des Eaux', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Collège Mariama Niasse', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'École 11', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Tally Boubess, 848', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Tally Boumak, 191', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Grand Mosquée De Pikine', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Tribunal De Guediawaye', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Collége Serigne', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Stade Amadou', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Police De Guediawaye', 'retour', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Pompiers De Guédiawaye', 'retour', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Bvard. Tall / Route Corniche', 'retour', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Mairie Hamo5', 'retour', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('2A', 'Gare Routière Daroukhane', 'retour', 19) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Correction', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Bvar. Tapée / Rue 08', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Bvar. Tapée / Rue 18', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Université Hamptate', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Ecolé Primaire', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Gy-101, 13', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Samu Municipal', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Marché Dior', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Pa12-33', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Marché', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Mosquée De Cambaréne', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Ciméterie De Seydina', 'aller', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Terminus 6 - 79', 'aller', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Correction', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Bvar. Tapée / Rue 08', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Bvar. Tapée / Rue 18', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Université Hamptate', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Ecolé Primaire', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Gy-101, 13', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Samu Municipal', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Marché Dior', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Pa12-33', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Marché', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Mosquée De Cambaréne', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Ciméterie De Seydina', 'retour', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('6C', 'Terminus 6 - 79', 'retour', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Correction', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Cimetiére', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Hopital Fann', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Lycée Thierno', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Chef D'' Etat Major', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Hopital Militaire', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Lycée Mermoz', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'École Des Officiers', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Correction', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Cimetiére', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Hopital Fann', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Lycée Thierno', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Chef D'' Etat Major', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Hopital Militaire', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'Lycée Mermoz', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('7O', 'École Des Officiers', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Cem Mame Thierno', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'École Nationale', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Ecolé Khar Yalla', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Camp Sekou Mballo', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Mosquée Arafat', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Collége Cardinal', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Stade', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Hopital', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Aeroport', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Cem Mame Thierno', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'École Nationale', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Ecolé Khar Yalla', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Camp Sekou Mballo', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Mosquée Arafat', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Collége Cardinal', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Stade', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Hopital', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('8A', 'Aeroport', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Correction', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Cimetiére', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Bvar. Tapée / Rue 08', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Paroisse Saint Dominique', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Mosquée Grand - Dakar', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Mosquée', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Ecolé Primaire', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Mosquée Liberté 6', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Ciudad De Los Deporte', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Correction', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Cimetiére', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Bvar. Tapée / Rue 08', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Paroisse Saint Dominique', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Mosquée Grand - Dakar', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Mosquée', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Ecolé Primaire', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Mosquée Liberté 6', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('9L', 'Ciudad De Los Deporte', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Correction', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Cimetiére', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Hopital Fann', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Lycée Thierno', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'École Nationale De Police', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Bis 45 / Lib-168', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Centre Sociale', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Terminus Liberté 5', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Correction', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Cimetiére', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Hopital Fann', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Lycée Thierno', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'École Nationale De Police', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Bis 45 / Lib-168', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Centre Sociale', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('10L', 'Terminus Liberté 5', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Gare De Dakar', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Hlm V', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Collège Mariama Niasse', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'École 11', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Sips', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Poste De Santé Gueye', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'École Alioune Gaye', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Centre De Santé', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Brigade De Gendarmerie', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Carrefour Mbao', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Centre Equestre', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Gare De Keur Massar', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Garage Keur Massar', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Roue De Keur Massar / Bvar. Ainoumady', 'aller', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'École Keur Massar', 'aller', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Gare Leclerc', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Gare De Dakar', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Hlm V', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Collège Mariama Niasse', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'École 11', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Sips', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Poste De Santé Gueye', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'École Alioune Gaye', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Centre De Santé', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Brigade De Gendarmerie', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Carrefour Mbao', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Centre Equestre', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Gare De Keur Massar', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Garage Keur Massar', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'Roue De Keur Massar / Bvar. Ainoumady', 'retour', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('11K', 'École Keur Massar', 'retour', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Place De L'' Independance', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Gare De Dakar', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Camp Lemonier', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Ecolé Marítime', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Camp', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Cercle De L''Etrier', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Station D''Épuration De Cambérene', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Marché De Cambérene', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Lycée Parcelles', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Centre Sauvegarde De Pikine-Guediawaye', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Stade Amadou', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Police De Guediawaye', 'aller', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Pompiers De Guédiawaye', 'aller', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Grande Mosquée De Guédiawaye', 'aller', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Bvard. Tall / Route Corniche', 'aller', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Terminus De Guédiawaye', 'aller', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Place De L'' Independance', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Gare De Dakar', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Camp Lemonier', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Ecolé Marítime', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Camp', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Cercle De L''Etrier', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Station D''Épuration De Cambérene', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Marché De Cambérene', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Lycée Parcelles', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Centre Sauvegarde De Pikine-Guediawaye', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Stade Amadou', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Police De Guediawaye', 'retour', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Pompiers De Guédiawaye', 'retour', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Grande Mosquée De Guédiawaye', 'retour', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Bvard. Tall / Route Corniche', 'retour', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('12G', 'Terminus De Guédiawaye', 'retour', 19) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Place De L'' Independance', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Gare De Dakar', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Ecolé', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Mosquée', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Ave. Mbacké / Rue 29', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Terminus Liberté 5', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Place De L'' Independance', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Gare De Dakar', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Ecolé', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Mosquée', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Ave. Mbacké / Rue 29', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('13L', 'Terminus Liberté 5', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Correction', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Cimetiére', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Hopital Fann', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Lycée Thierno', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Chef D'' Etat Major', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Hopital Militaire', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Lycée Mermoz', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Cimetiére Musulmán De Ouakam', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'La Poste', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Marché Salagne Salagne', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Dioulikay', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'King Fahd Palace Hotel', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Camp Vert', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Gare Leclerc', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Correction', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Cimetiére', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Hopital Fann', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Lycée Thierno', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Chef D'' Etat Major', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Hopital Militaire', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Lycée Mermoz', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Cimetiére Musulmán De Ouakam', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'La Poste', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Marché Salagne Salagne', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Dioulikay', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'King Fahd Palace Hotel', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('14C', 'Camp Vert', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Gare De Rufisque', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Jardín Public', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Hotel Castel', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Zac Mbao', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Mairie De Grand Mbao', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Keur Mbaye Mosquée', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Keur Mbaye Centre', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Carrefour Keur Massar', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Carrefour Mbao', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Brigade De Gendarmerie', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Centre De Santé', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'École Alioune Gaye', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Poste De Santé Gueye', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Sips', 'aller', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Terrain Maracana', 'aller', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Centre Hospitalier De Hann', 'aller', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Zoo', 'aller', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Cité Tp Som, 10', 'aller', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Hlm V', 'aller', 19) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Gare Palais', 'aller', 20) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Gare Marítime De Rufisque', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Gare De Rufisque', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Jardín Public', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Hotel Castel', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Zac Mbao', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Mairie De Grand Mbao', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Keur Mbaye Mosquée', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Keur Mbaye Centre', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Carrefour Keur Massar', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Carrefour Mbao', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Brigade De Gendarmerie', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Centre De Santé', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'École Alioune Gaye', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Poste De Santé Gueye', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Sips', 'retour', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Terrain Maracana', 'retour', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Centre Hospitalier De Hann', 'retour', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Zoo', 'retour', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Cité Tp Som, 10', 'retour', 19) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Hlm V', 'retour', 20) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('15R', 'Gare Palais', 'retour', 21) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Place De L'' Independance', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Gare De Dakar', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Camp Lemonier', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Ecolé Marítime', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Camp', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Cercle De L''Etrier', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Zoo', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Cem De Hann', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Sips', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Cem Thiaroye', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'École Camp Thiaroye', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Centre Commerciale De Thiaroye', 'aller', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Rute De Niaye / Route De Malika', 'aller', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Arret De Bus', 'aller', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Mosquée De Yeumbeul', 'aller', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Complexe Islamique', 'aller', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'École Yeumbeul', 'aller', 19) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Cimetiére De Malika', 'aller', 20) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Terminus Malika', 'aller', 21) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Place De L'' Independance', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Gare De Dakar', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Camp Lemonier', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Ecolé Marítime', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Camp', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Cercle De L''Etrier', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Zoo', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Cem De Hann', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Sips', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Cem Thiaroye', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'École Camp Thiaroye', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Centre Commerciale De Thiaroye', 'retour', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Rute De Niaye / Route De Malika', 'retour', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Arret De Bus', 'retour', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Mosquée De Yeumbeul', 'retour', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Complexe Islamique', 'retour', 19) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'École Yeumbeul', 'retour', 20) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Cimetiére De Malika', 'retour', 21) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16A', 'Terminus Malika', 'retour', 22) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Place De L'' Independance', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Gare De Dakar', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Camp Lemonier', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Ecolé Marítime', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Camp', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Cercle De L''Etrier', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Cité Tp Som, 10', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Collège Mariama Niasse', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'École 11', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Sips', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Cem Thiaroye', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'École Camp Thiaroye', 'aller', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Centre Commerciale De Thiaroye', 'aller', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Rute De Niaye / Route De Malika', 'aller', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Arret De Bus', 'aller', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'École Boune', 'aller', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Marché De Malika', 'aller', 19) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Cimetiére De Malika', 'aller', 20) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Place De L'' Independance', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Gare De Dakar', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Camp Lemonier', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Ecolé Marítime', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Camp', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Cercle De L''Etrier', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Cité Tp Som, 10', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Collège Mariama Niasse', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'École 11', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Sips', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Cem Thiaroye', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'École Camp Thiaroye', 'retour', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Centre Commerciale De Thiaroye', 'retour', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Rute De Niaye / Route De Malika', 'retour', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Arret De Bus', 'retour', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'École Boune', 'retour', 19) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Marché De Malika', 'retour', 20) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('16B', 'Cimetiére De Malika', 'retour', 21) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Radisson Hotel', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Cimetiére', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Maison D''Arret', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Place De L'' Independance', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Gare De Dakar', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Ecolé', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Mosquée', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Ave. Mbacké / Rue 29', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Terminus Liberté 5', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Terminus Liberté 5', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Radisson Hotel', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Cimetiére', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Maison D''Arret', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Place De L'' Independance', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Gare De Dakar', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Ecolé', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Mosquée', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('18L', 'Ave. Mbacké / Rue 29', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Ave. Mbacké / Rue 29', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Mosquée', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Cem Mame Thierno', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Triangle Sud', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Correction', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Cimetiére', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Radisson Hotel', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Mz-134', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Terminus Liberté 5', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Terminus Liberté 5', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Ave. Mbacké / Rue 29', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Mosquée', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Cem Mame Thierno', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Triangle Sud', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Correction', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Cimetiére', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Radisson Hotel', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('20L', 'Mz-134', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Pa12-33', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Pa13-12', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Pa08-02', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Ecolé Soprim', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Routes Des Niayes, 373', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Marché De Grand Yoff', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Mosquée', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Marché', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Ave. Mbacké / Rue 29', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Lycée J.F.K.', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Cem Mame Thierno', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Triangle Sud', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Gare Palais', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Terminus Parcelles - Assainies', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Pa12-33', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Pa13-12', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Pa08-02', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Ecolé Soprim', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Routes Des Niayes, 373', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Marché De Grand Yoff', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Mosquée', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Marché', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Ave. Mbacké / Rue 29', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Lycée J.F.K.', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Cem Mame Thierno', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Triangle Sud', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('23P', 'Gare Palais', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Clinique Du Cap', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Hôpital Le Dantec', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Place De L'' Independance', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Gare De Dakar', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Hlm V', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Collège Mariama Niasse', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'École 11', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Sips', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Poste De Santé Gueye', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'École Alioune Gaye', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Centre De Santé', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Brigade De Gendarmerie', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Carrefour Mbao', 'aller', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Poste De Santé', 'aller', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'École Mour Seck', 'aller', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Lycée De Mbao', 'aller', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'École Wassour', 'aller', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Gare Palais', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Clinique Du Cap', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Hôpital Le Dantec', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Place De L'' Independance', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Gare De Dakar', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Hlm V', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Collège Mariama Niasse', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'École 11', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Sips', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Poste De Santé Gueye', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'École Alioune Gaye', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Centre De Santé', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Brigade De Gendarmerie', 'retour', 13) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Carrefour Mbao', 'retour', 14) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Poste De Santé', 'retour', 15) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'École Mour Seck', 'retour', 16) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'Lycée De Mbao', 'retour', 17) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('45M', 'École Wassour', 'retour', 18) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'Gare De Dakar', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'École Nationale', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'Gy-101, 13', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'Salam Inmobilier', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'École Hlm Grand Yoff', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'Gare Leclerc', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'Gare De Dakar', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'École Nationale', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'Gy-101, 13', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'Salam Inmobilier', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('121H', 'École Hlm Grand Yoff', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Gare De Rufisque', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Mosquée Jakka', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Hopital De Rufisque', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Notre Dame De Sangalkam', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Mosquée', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Centre De Tortues Du Sénégal', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'École Privée', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Hotel De Ville', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Marché De Bambilor', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Terrain Football', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Gorom', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Terminus Rufisque', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Gare De Rufisque', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Mosquée Jakka', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Hopital De Rufisque', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Notre Dame De Sangalkam', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Mosquée', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Centre De Tortues Du Sénégal', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'École Privée', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Hotel De Ville', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Marché De Bambilor', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Terrain Football', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('208G', 'Gorom', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Dioulikay', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Université Polytechnique De L''Ouest Africain', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Stade De Ngor', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Aéroport', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Hopital Senghor', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Gy-101, 13', 'aller', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Ecolé Khar Yalla', 'aller', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Camp Sekou Mballo', 'aller', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Mosquée Arafat', 'aller', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Collége Cardinal', 'aller', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Pavilion', 'aller', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Aéroport International Blaise-Diagne', 'aller', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Dioulikay', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Université Polytechnique De L''Ouest Africain', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Stade De Ngor', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Aéroport', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Hopital Senghor', 'retour', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Gy-101, 13', 'retour', 6) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Ecolé Khar Yalla', 'retour', 7) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Camp Sekou Mballo', 'retour', 8) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Mosquée Arafat', 'retour', 9) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Collége Cardinal', 'retour', 10) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Pavilion', 'retour', 11) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('401', 'Aéroport International Blaise-Diagne', 'retour', 12) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'Stade Municipal', 'aller', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'École 6', 'aller', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'École De Officiers', 'aller', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'Quartier Geille', 'aller', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'Les Voies De I''Alternance, 155', 'aller', 5) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'Stade Municipal', 'retour', 1) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'École 6', 'retour', 2) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'École De Officiers', 'retour', 3) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'Quartier Geille', 'retour', 4) ON CONFLICT DO NOTHING;
INSERT INTO arrets (ligne_numero, nom, direction, ordre) VALUES ('319', 'Les Voies De I''Alternance, 155', 'retour', 5) ON CONFLICT DO NOTHING;
